In [6]:
import numpy as np
import time

a = np.zeros(4); print(f"np.zeros:--> a = {a}, shape:--> a = {a.shape}")
b = np.zeros(4,); print(f"np.zeros:--> b = {b}, shape:--> b = {b.shape}")
c = np.random.random_sample(4); print(f"Random sample:--> c = {c}, shape of c:--> {c.shape} ")

np.zeros:--> a = [0. 0. 0. 0.], shape:--> a = (4,)
np.zeros:--> b = [0. 0. 0. 0.], shape:--> b = (4,)
Random sample:--> c = [0.89577023 0.70319547 0.82352334 0.09508787], shape of c:--> (4,) 


In [10]:
a = np.arange(4); print(a)
a = np.arange(4.); print(a)
a = np.random.rand(4); print(a)

[0 1 2 3]
[0. 1. 2. 3.]
[0.07072228 0.32902442 0.18581286 0.51321621]


In [34]:
print("--------1D ARRAY--------")
a = np.arange(10)
print(a)
print(a[2].shape)
print("--------2D ARRAY--------")
b = np.array([[10,20,30],[40,50,60],[70,80,90]])
print(b)
print(b[2].shape)
print("----ELEMENT FROM END----")
print(a[-2])  #the counting from the end starts from '-1' and '0' unlike the couting from the beginning.

--------1D ARRAY--------
[0 1 2 3 4 5 6 7 8 9]
()
--------2D ARRAY--------
[[10 20 30]
 [40 50 60]
 [70 80 90]]
(3,)
----ELEMENT FROM END----
8


In [35]:
print("----SLICING----")
print(a[1:10:3])
print("--PRINTING NEGATIVE VALUES--")  #this is called slicing--> syntax = [start:stop:step]
print(-a)
print("--SUM OF DIGITS--")
b = np.sum(a)
print(b)
print("----MEAN OF DIGITS----")
c = np.mean(a)
print(c)
print("----OPERTION----")
d = a**2
print(d)

----SLICING----
[1 4 7]
--PRINTING NEGATIVE VALUES--
[ 0 -1 -2 -3 -4 -5 -6 -7 -8 -9]
--SUM OF DIGITS--
45
----MEAN OF DIGITS----
4.5
----OPERTION----
[ 0  1  4  9 16 25 36 49 64 81]
